resolver: lts-15.11
extra-deps:
- git: https://github.com/mbj/mprelude
  commit: 451e3c2bed257c42e45dfb00d66376285cfaa56f
- git: https://github.com/mbj/source-constraints
  commit: 882efed7bef03fcc92985b1e76c0056731739e82
- git: https://github.com/mbj/tasty
  commit: 6b884dc97902feaf6e81ad46f3cc905eb122e5d6
  subdirs:
  - core
- git: https://github.com/mbj/tasty-mgolden
  commit: 6f18ae430acf51dd2f2cc92d67cf2c3d3a2ae3f1
